[general]
ADMIN_PASSWORD = "admin123"
RECEPTIONIST_PASSWORD = "recep123"
HEAD_NURSE_PASSWORD = "nurse123"
ACCOUNTANT_PASSWORD = "account123"
SERVICE_COORDINATOR_PASSWORD = "service123"

[database]
DB_HOST = "localhost"
DB_NAME = "hospital_management"
DB_USER = "postgres"
DB_PASSWORD = "nandini@108"
